### PR TITLE
Feature: change cursor style1

### PR DESCRIPTION
**Pull request by lerrybe**
🚀 [Related Issue: #14]

### Preview

https://github.com/hunkim98/dotting/assets/71599639/d8616b12-618c-4885-a4ab-0719132ea0f7

<br/>

### Changes
Implement cursor style when mouse move

## Write a title of your change

- **[🔗Other] implements styleMouseCursor function `Canvas/Editor.tsx`**

  - When mouseMove, the cursor style is determined. (dot, eraser, paint bucket, resize) 

<br/>

## Notes

Question
- Currently, the cursor style is determined when you move the mouse.
(This is because I wanted the cursor to change even when the value of the hoveredButton's value changed.)
- But another way is to change it only **when 'setBrushTool' called**. 
This method is expected to significantly reduce the calling of styleMouseCursor function.

Which is better to implement?

<br/>

## Next Up?

- I will continue to develop or refactor this feature.

### CODE REVIEW

**Comment by hunkim98** [comment]
I believe changing cursor when `setBrushTool` is called would be better. I have checked some examples of other repositories.

1. tldraw
- https://github.com/tldraw/tldraw/blob/16b7b07e1a8221f9548dcb4ef35749cc3a29cb4c/packages/editor/src/lib/app/statechart/TLZoomTool/TLZoomTool.ts#L14-L25

2. react-artboard
-  https://github.com/ascorbic/react-artboard/blob/fd2c04910eb65ab707b91e8dffd532b0a8dcbe03/src/tools/shading/useShadingBrush.ts#L74
- https://github.com/ascorbic/react-artboard/blob/fd2c04910eb65ab707b91e8dffd532b0a8dcbe03/src/tools/brush/useBrush.ts#L146

What was interesting is that tldraw did not use any custom svg cursors! Though the app itself has lots of tools, the developers seem to have used the css-supported basic cursors. tldraw only uses `crosshair` for drawing tools. Tldraw sets the cursors when tool is changed.

React-artboard seems to use a similar approach. They use `crosshair` for pen tool and a custom created `circleCursor` for other brushes. Check this [`cursor.ts`](https://github.com/ascorbic/react-artboard/blob/fd2c04910eb65ab707b91e8dffd532b0a8dcbe03/src/utils/cursors.ts#L1-L17) if you would like to find out how they implemented their own custom cursor. It seems that they have embedded the svg inside the typescript. That is actually one way you could use for custom cursors. React-artboard also sets the cursor when the tool is changed. React-artboard implemented the functionality to change brushes using hooks like `useMarker`, `useWaterMarke` and so on. When that hook is called cursor is changed.

You can also reference [`toonie.ts`](https://github.com/yorkie-team/toonie/blob/main/src/components/Editor/Toolbars/icons.tsx) to see how you can implement svg into a typescript variable. When there is a need to implement svgs into a project, I would go to (https://react-svgr.com/playground/?typescript=true0) and then copy and paste the original raw svg. The site returns a compressed version of the svg so that the code does not get too long. It comes in handy when you just want to embed the svg in the code!

By the way, great job!

**Review by hunkim98 — COMMENTED** [review]
Great work! I will leave it to you to decide whether we should use basic css cursors or svgs. By the way I believe it would be safe to use embedded svgs for using svg components! Using embedded ones comes in handy because we can style them easily when they are embedded. Plus, since our library is a typescript code, some static files might not be exported.🚀

If you want to merge this PR in the main branch and continue your work on this on another branch, you may proceed and merge this PR.

**Comment by Lee-Si-Yoon** [comment]
If you decided to default css style IMO deleting unused svg files would be better
+a) in UX approach tldraw's virtual cursor for erasor looks great. would there be no need for us to use virtual cursor? for example all same crosshair for different brush mode seems not to be the best

**Review by Lee-Si-Yoon — APPROVED** [review]

**Comment by hunkim98** [comment]
@Lee-Si-Yoon Tge cursor style can be later updated while @lerrybe works on issue #13 which is about using strategy pattern for controlling brush tools. Plus, it seemed to me that this cursor styling is less important compared to other major issues. We could later leave this svg styling issue to other contributors who joins this proejct as a good first issue. 

Thank you all for the great reviews!🚀

**Comment by hunkim98** [comment]
You are free to merge this PR. It would be great if you could `rebase and merge`.

**Comment by lerrybe** [comment]
@hunkim98 @Lee-Si-Yoon 
As @hunkim98 suggested, I think cursor-style part can be included while applying strategy patterns to the brush tool. Thank you for leaving a great review!

**Pull request merged**
